// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5aDUFl98luqdiQssig_JO1hRE6lnUCU8',
    appId: '1:193517349660:web:719ed4e8432fc2cb75e8d9',
    messagingSenderId: '193517349660',
    projectId: 'bookhealth-8bdcf',
    authDomain: 'bookhealth-8bdcf.firebaseapp.com',
    storageBucket: 'bookhealth-8bdcf.firebasestorage.app',
    measurementId: 'G-NF9N55XT9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZIhXN7sOFqwx8aQtr-x7UKqtosFnlKE',
    appId: '1:193517349660:android:28236cc805fb1aea75e8d9',
    messagingSenderId: '193517349660',
    projectId: 'bookhealth-8bdcf',
    storageBucket: 'bookhealth-8bdcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjj3W-DE9T-e-vVrE3NIeEFWAWCf9hJes',
    appId: '1:193517349660:ios:e8a31768eb4e1d7d75e8d9',
    messagingSenderId: '193517349660',
    projectId: 'bookhealth-8bdcf',
    storageBucket: 'bookhealth-8bdcf.firebasestorage.app',
    iosBundleId: 'com.example.bookhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjj3W-DE9T-e-vVrE3NIeEFWAWCf9hJes',
    appId: '1:193517349660:ios:e8a31768eb4e1d7d75e8d9',
    messagingSenderId: '193517349660',
    projectId: 'bookhealth-8bdcf',
    storageBucket: 'bookhealth-8bdcf.firebasestorage.app',
    iosBundleId: 'com.example.bookhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5aDUFl98luqdiQssig_JO1hRE6lnUCU8',
    appId: '1:193517349660:web:c18fa149d14d6b1e75e8d9',
    messagingSenderId: '193517349660',
    projectId: 'bookhealth-8bdcf',
    authDomain: 'bookhealth-8bdcf.firebaseapp.com',
    storageBucket: 'bookhealth-8bdcf.firebasestorage.app',
    measurementId: 'G-ZBDE4R3702',
  );
}
